### ISSUE TITLE
Provide an example with electron-forge

### ISSUE THREAD

**Issue by dj-fiorex** [poirierlouis/electron-bridge#3] opened 2023-03-07 22:00 UTC
Hello again,
I have a question that I think could be interesting for other people who are approaching electron for the first time and would like to follow all the best practices. thanks to your module it is much easier to follow electron's security practices. another very important tool to get started with electron is [electron-forge](https://www.electronforge.io/), which allows you to have an all-in-one solution for electron.
I tried the starter pack of electron-forge with typescript + webpack 
`yarn create electron-app my-new-app --template=webpack-typescript`
then i added the package
`yarn add @lpfreelance/electron-bridge`
then in main.ts i added the DialogService for example
```
  // Create bridge service.
  bridgeService = new BridgeService();

  // Append bridges that you need and register all IPC handlers.
  bridgeService.add(new DialogBridge()).registerAll();
```
and in preload.ts
```
import { PreloadService } from "@lpfreelance/electron-bridge/preload";
const preloadService = new PreloadService();
preloadService.add("dialog").expose();
```
but i receive an error in the renderer process
![image](https://user-images.githubusercontent.com/15034741/223562346-522de177-0a72-4cd6-b674-47f579bc3c87.png)

I don't understand why this error is happening, please can you help me?

If i look at the output files, precisely in .webpack/renderer/main_window/preload.js, there is this code:
```
/************************************************************************/
/******/ 	/* webpack/runtime/compat */
/******/ 	
/******/ 	if (typeof __webpack_require__ !== 'undefined') __webpack_require__.ab = __dirname + "/native_modules/";
/******/ 	
/************************************************************************/
```
and i think is webpack fault for this use of __dirname

UPDATE
So after some digging in the webpack configurations i think i now understand the problem:
in the files `webpack.main.config.ts` and `webpack.renderer.config.ts`  in the rules section the two files import the same rules from another file `webpack.rules.ts`. I think the problem is this rule, because if i omit this in the renderer config it works:
```
  {
    test: /[/\\]node_modules[/\\].+\.(m?js|node)$/,
    parser: { amd: false },
    use: {
      loader: "@vercel/webpack-asset-relocator-loader",
      options: {
        outputAssetBase: "native_modules",
      },
    },
  },
```
Do you have any clue?

**Comment by poirierlouis** [comment] 2023-03-08 09:20
Hi,

Thank you for this feedback, I did not know `electron-forge` could do more than just publish an electron application.
I'm not familiar with this package and how their template can work or not with `electron-bridge`.

It will need analysis. So far thank you for pointing me out to the `webpack.rules.ts`!

**Comment by dj-fiorex** [comment] 2023-03-08 12:04
Thanks again, i created a boilerplate where everythings works good, if you want to have a look
https://github.com/dj-fiorex/awesome-electron-forge-boilerplate

**Comment by poirierlouis** [comment] 2023-03-08 13:21
Well, it is not clear to me what you changed to make it work in your template. Could you be more specific?
I tried to replace `@vercel/webpack-asset-relocator-loader` with `@timfish/webpack-asset-relocator-loader` but it is still not working (in rules and in packages.json). I don't think it is the problem-solver, moreover it relies on an old version of the package it wraps which might not be optimal.

Trying your first solution did workout for me. My understanding so far is that the following rules allows usage of Node.js modules into the renderer side of your Electron project (along with `nodeIntegration: true`) :
```JavaScript
  // Add support for native node modules
  {
    // We're specifying native_modules in the test because the asset relocator loader generates a
    // "fake" .node file which is really a cjs file.
    test: /native_modules[/\\].+\.node$/,
    use: 'node-loader',
  },
  {
    test: /[/\\]node_modules[/\\].+\.(m?js|node)$/,
    parser: { amd: false },
    use: {
      loader: '@vercel/webpack-asset-relocator-loader',
      options: {
        outputAssetBase: 'native_modules',
      },
    },
  },
```

It seems that the `__dirname` error shows up with the above rule because it attempts to use Node.js feature in the renderer. Which is forbidden and not the expected behaviour when using `electron-bridge` (and `nodeIntegration: false, contextIsolation: true`).

I think you can go with the default behaviour of `electron-forge` and use native modules without the need to use this plugin (when not targeting web). Otherwise, if you want to secure things, you remove the rule and use this plugin to only expose the native features you which to expose.

**Comment by poirierlouis** [comment] 2023-03-08 16:54
Closing now that [demo-forge/](https://github.com/poirierlouis/electron-bridge/tree/master/demo-forge) shows how to use `electron-forge`, with an explanation in main README.

**Closed as completed by poirierlouis** 2023-03-08 16:54 UTC
Labels: documentation, enhancement, good first issue
